const data = {
    products:[
        {
            _id:'1',
            name:'Anillo con Esmeralda',
            category: 'Rings',
            image: '/images/img1.png',
            price: '250',
            brand: 'Esmeralda',
            rating: 4.5,
            numReviews: 12,
            description: 'High quality product',
        },
        {
            _id:'2',
            name:'Collar con Esmeralda y Circonios',
            category: 'Collar',
            image: '/images/img5.png',
            price: '350',
            brand: 'Esmeralda',
            rating: 5.0,
            numReviews: 10,
            description: 'High quality product',
        },
        {
            _id:'3',
            name:'Anillo imitación Esmeralda',
            category: 'Rings',
            image: '/images/img3.png',
            price: '25',
            brand: 'Esmeralda',
            rating: 4.5,
            numReviews: 12,
            description: 'High quality product',
        },
        {
            _id:'4',
            name:'Anillo de compromiso en plata con amatista',
            category: 'Collar',
            image: '/images/img4.png',
            price: '350',
            brand: 'Esmeralda',
            rating: 5.0,
            numReviews: 10,
            description: 'High quality product',
        },
        {
            _id:'5',
            name:'Argollas de matrimonio',
            category: 'Rings',
            image: '/images/img2.png',
            price: '150',
            brand: 'Esmeralda',
            rating: 4.5,
            numReviews: 8,
            description: 'High quality product',
        },
        {
            _id:'6',
            name:'Anillo en plata con Ruby ',
            category: 'Collar',
            image: '/images/img6.png',
            price: '250',
            brand: 'Esmeralda',
            rating: 5.0,
            numReviews: 10,
            description: 'High quality product',
        },
    ],
};

export default data;